FROM python:alpine3.14
# can you find a lighter image?

WORKDIR /app

# copy the requirements file in the workdir
COPY requirements.txt /app/

# install the Python requirements
RUN pip install -r requirements.txt

# copy the app files and directories
ADD . /app/

# start movie.py when the container is started
ENTRYPOINT ["python", "-u", "schedule.py"]
